### ISSUE TITLE
Bugs in 2d code?

### ISSUE THREAD

**Issue by beckermr** [devonmpowell/r3d#13] opened 2019-04-23 14:07 UTC
Hey @devonmpowell! Matt Becker here from Stanford waaaaay back. 

@esheldon and I are trying to use the 2d routines to do some exact image coadding and finding some weird things. Can you help us with a few things?

1. What is the convention on grid edges and cell centers? Is cell (0, 0) on the grid centered at (0.5, 0.5) or (0, 0)? 

2. In 2d we have found that the code only paints the corners of the triangle and not the interior. Is this correct? It seems like a bug.

**Comment by beckermr** [comment] 2019-04-23 14:18
It is this output that I do not get:

For this square:

```
  vertex 0: pos = ( 2.2500000000e+00 , 3.0000000000e-01 ), nbrs = 1 3
  vertex 1: pos = ( 3.2500000000e+00 , 3.0000000000e-01 ), nbrs = 2 0
  vertex 2: pos = ( 3.2500000000e+00 , 1.3000000000e+00 ), nbrs = 3 1
  vertex 3: pos = ( 2.2500000000e+00 , 1.3000000000e+00 ), nbrs = 0 2
```

I get the following for the area after rasterization:
```
  val: 0 0 0.075000
  val: 0 1 0.175000
  val: 1 0 0.225000
  val: 1 1 0.525000
```

I would have expected the area overlap for the lower-left cell (0 0 in the grid) to be 0.75*0.7 = 0.525.

**Comment by beckermr** [comment] 2019-04-23 14:48
Here is an example where it seems to be missing cells.

The polygon:

```
  vertex 0: pos = ( 2.2500000000e+00 , 3.0000000000e-01 ), nbrs = 1 3
  vertex 1: pos = ( 4.2500000000e+00 , 3.0000000000e-01 ), nbrs = 2 0
  vertex 2: pos = ( 4.2500000000e+00 , 1.3000000000e+00 ), nbrs = 3 1
  vertex 3: pos = ( 2.2500000000e+00 , 1.3000000000e+00 ), nbrs = 0 2
```

Result for the area:

```
  val: 0 0 0.375000
  val: 0 1 0.875000
  val: 1 0 0.000000
  val: 1 1 0.000000
  val: 2 0 0.225000
  val: 2 1 0.525000
```

**Comment by devonmpowell** [comment] 2019-04-23 14:53
Hey Matt, 

Nice to hear from you and glad r3d is getting some use!

To answer your first question, the convention is in that the cells vertices are at (i*dx, j*dy), etc. So the cell would be centered at (0.5*dx, 0.5*dy)

What you describe does not sound right... If you send me a code snippet from your use case I'd be happy to take a closer look. 

Cheers,
Devon

**Comment by beckermr** [comment] 2019-04-23 15:03
Hmmmmm. My code is in cython w/ python tests. I can try and write a simple C example.

**Comment by devonmpowell** [comment] 2019-04-23 15:08
No problem, you can also just send me a cython routine.

**Comment by beckermr** [comment] 2019-04-23 15:13
See the PR here: https://github.com/beckermr/coaddit/pull/2

My interface is at coaddit/r3d/_r3d_interface.pyx and the test cases are in the tests folder coaddit/r3d/tests/test_r3d.py

Note that I am doing a transpose and axis reversal to account for the weird ordering thing I noticed above. There are print statements in the cython that show the raw output.

**Comment by esheldon** [comment] 2019-04-23 15:36
I also saw this with a test I ran completely independently, an example rasterization is attached showing only the corners get painted
![test-grid](https://user-images.githubusercontent.com/621661/56595080-fda13100-65bb-11e9-83ca-fa0ef55def90.png)

**Comment by devonmpowell** [comment] 2019-04-23 15:39
Could you try a quick test? Just reorder the vertices from CCW to
clockwise... I don’t remember which convention I implemented but it’s
possible that this is the problem.

**Comment by esheldon** [comment] 2019-04-23 15:40
This is a straight run of your `test_rasterization` , I did not set any verticies by hand.

**Comment by devonmpowell** [comment] 2019-04-23 15:41
Ah okay. I’ll see what I can figure out.

**Comment by esheldon** [comment] 2019-04-23 15:45
The only thing I did change for the above run was the seed for srand to 350 and the grid size set to 30 (I was playing with various parameters)

**Comment by devonmpowell** [comment] 2019-04-24 10:27
After doing some of my own tests, it looks like this is a real bug in the code. Not sure why I haven't noticed this long ago. I will let you know when I find the problem and push a fix.

**Comment by devonmpowell** [comment] 2019-04-24 12:55
I believe the problem is fixed now -- It was a sign error in computing the vertex/clip plane distance in r2d_split. I have pushed the changes as well as fixed the &->&& bugs that Erin found.
Thanks and let me know how it goes!
Devon

**Closed as completed** 2019-06-28 12:50 UTC
